// Mocks generated by Mockito 5.4.6 from annotations
// in taro/test/taro_loader_network_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:taro/src/taro_loader_network.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaroHttpResponse_0 extends _i1.SmartFake
    implements _i2.TaroHttpResponse {
  _FakeTaroHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaroHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaroHttpClient extends _i1.Mock implements _i2.TaroHttpClient {
  @override
  _i3.Future<_i2.TaroHttpResponse> get({
    required Uri? uri,
    required Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #uri: uri,
            #headers: headers,
          },
        ),
        returnValue:
            _i3.Future<_i2.TaroHttpResponse>.value(_FakeTaroHttpResponse_0(
          this,
          Invocation.method(
            #get,
            [],
            {
              #uri: uri,
              #headers: headers,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.TaroHttpResponse>.value(_FakeTaroHttpResponse_0(
          this,
          Invocation.method(
            #get,
            [],
            {
              #uri: uri,
              #headers: headers,
            },
          ),
        )),
      ) as _i3.Future<_i2.TaroHttpResponse>);
}
