version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Asia/Tokyo"
    groups:
      github-actions-official:
        patterns:
          - "actions/*"
