// Mocks generated by Mockito 5.4.6 from annotations
// in taro/test/src/taro_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:taro/src/taro_loader_network.dart' as _i2;
import 'package:taro/src/taro_loader_storage.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaroHttpClient_0 extends _i1.SmartFake
    implements _i2.TaroHttpClient {
  _FakeTaroHttpClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaroLoaderNetwork].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaroLoaderNetwork extends _i1.Mock implements _i2.TaroLoaderNetwork {
  @override
  _i2.TaroHttpClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeTaroHttpClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeTaroHttpClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.TaroHttpClient);

  @override
  _i3.Future<({_i4.Uint8List bytes, String contentType, DateTime? expireAt})?>
      load({
    required String? url,
    required Map<String, String>? headers,
    bool? checkMaxAgeIfExist = false,
    bool? ifThrowMaxAgeHeaderError = false,
    Duration? customCacheDuration,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #load,
              [],
              {
                #url: url,
                #headers: headers,
                #checkMaxAgeIfExist: checkMaxAgeIfExist,
                #ifThrowMaxAgeHeaderError: ifThrowMaxAgeHeaderError,
                #customCacheDuration: customCacheDuration,
              },
            ),
            returnValue: _i3.Future<
                ({
                  _i4.Uint8List bytes,
                  String contentType,
                  DateTime? expireAt
                })?>.value(),
            returnValueForMissingStub: _i3.Future<
                ({
                  _i4.Uint8List bytes,
                  String contentType,
                  DateTime? expireAt
                })?>.value(),
          ) as _i3.Future<
              ({
                _i4.Uint8List bytes,
                String contentType,
                DateTime? expireAt
              })?>);
}

/// A class which mocks [TaroLoaderStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaroLoaderStorage extends _i1.Mock implements _i5.TaroLoaderStorage {
  @override
  _i3.Future<_i4.Uint8List?> load({required String? url}) =>
      (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
          {#url: url},
        ),
        returnValue: _i3.Future<_i4.Uint8List?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.Uint8List?>.value(),
      ) as _i3.Future<_i4.Uint8List?>);

  @override
  _i3.Future<void> save({
    required String? url,
    required _i4.Uint8List? bytes,
    required String? contentType,
    required DateTime? expireAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
          {
            #url: url,
            #bytes: bytes,
            #contentType: contentType,
            #expireAt: expireAt,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
