name: pr review

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@a66a3ff390f07e139285012467025b12778e2b9f # v1.2.0
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b # v3.0.0

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@a66a3ff390f07e139285012467025b12778e2b9f # v1.2.0
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@a66a3ff390f07e139285012467025b12778e2b9f # v1.2.0
      - run: flutter pub get
      - run: flutter test
