name: pr review

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@e869444283cdc5705870adddd145d42cd1cfd627 # v1.1.2
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b # v3.0.0

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@e869444283cdc5705870adddd145d42cd1cfd627 # v1.1.2
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@e869444283cdc5705870adddd145d42cd1cfd627 # v1.1.2
      - run: flutter pub get
      - run: flutter test
