name: pr review

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: koji-1009/setup-flutter@6684b1e2693265f44314b7ec18935073116a2241 # v1.3.1
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b # v3.0.0

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: koji-1009/setup-flutter@6684b1e2693265f44314b7ec18935073116a2241 # v1.3.1
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: koji-1009/setup-flutter@6684b1e2693265f44314b7ec18935073116a2241 # v1.3.1
      - run: flutter pub get
      - run: flutter test
